### ISSUE TITLE
Epic Generator

### ISSUE THREAD

**Issue by mme1950** [ASJeton/Willkommen#2]
Ich habe, wie ich glaube, den epic-generator eingebunden und habe ein Label "epic" erzeugt.
Dann soll man HTML-Kommentare wie `<!-- EPIC:DATA #1 #2 -->` eintragen um die Liste der zu dem Epic gehörenden Tickets zu generieren.
https://github.com/organizations/ASJeton/settings/installations/13831911

Hast du eine Idee warum er nicht funktioniert?

**Comment by daniel-richter** [comment]
Hm, keine Ahnung.

Aber ehrlich gesagt würde ich die ganze Sachen nicht total over-engineeren. Die Gruppe der IT-ler kennt vermutlich den Umgang mit Labeln, aber aufgrund der Reaktionen gestern denke ich, dass man das so einfach und mit so wenig Lernbedarf wie möglich einrichten sollte, um die Leute nicht zu überfordern. Denn wer weiß denn schon, was ein "Epic" ist.

Eine Übersicht aller Issues kann man z.B. auch alternativ mit einem Filter bekommen. Einfach auf ein Label klicken und schon sieht man nur die Issues, die dieses Label haben. Da braucht man meiner Meinung nach nicht noch ein Zusatz-Issue, dass alles zusammenfasst.

Alternativ/Zusätzlich ist vielleicht das einfachste für Neueinsteiger, die Projekte-Seite zu verwenden. https://github.com/ASJeton/Willkommen/projects/1
Da kann man dann Issues oder Notizen hin und her ziehen und sieht dann auch in den Issues vermerkt, wenn es eine Änderung gab.
Spalten können da z.B. die einzelnen Boote oder Kanban-mäßig der Bearbeitungs-Status sein.

**Comment by mme1950** [comment]
OK, du hast eigentlich recht. Dann muss man, wenn man unbedingt ein Übersichtsticket braucht, die Liste manuell pflegen.
